groups:
  sinks:
  - enabled: true
    name: All
    sinks:
    - Livingroom
    - Bedroom
    - Bathroom
    - Office
    volume: 1.0
  - enabled: true
    name: Bedroom Group
    sinks:
    - Bedroom
    - Bathroom
    volume: 1.0
  sources:
  - enabled: true
    name: Music
    sources:
    - Server
    volume: 1.0
routes:
- enabled: true
  name: Music to All
  sink: All
  source: Music
  volume: 1.0
- enabled: true
  name: Office
  sink: Office
  source: Office PC
  volume: 1.0
- enabled: true
  name: Office 2
  sink: Office
  source: Office PC Management VLAN
  volume: 1.0
- enabled: true
  name: Office to all
  sink: All
  source: Office PC
  volume: 1.0
- enabled: true
  name: Livingroom
  sink: Livingroom
  source: Livingroom PC
  volume: 1.0
- enabled: false
  name: Livingroom to All
  sink: All
  source: Livingroom PC
  volume: 1.0
- enabled: true
  name: Office to Phone
  sink: Phone
  source: Office PC
  volume: 1.0
sinks:
- enabled: true
  ip: 192.168.3.178
  name: Livingroom
  port: 4010
  volume: 0.47
- enabled: true
  ip: 192.168.3.111
  name: Bedroom
  port: 4010
  volume: 1.0
- enabled: true
  ip: 192.168.3.102
  name: Bathroom
  port: 4010
  volume: 1.0
- enabled: true
  ip: 192.168.3.153
  name: Office
  port: 4010
  volume: 1.0
- enabled: true
  ip: 192.168.3.106
  name: Phone
  port: 4011
  volume: 1.0
sources:
- enabled: true
  ip: 192.168.3.119
  name: Server
  volume: 1.0
- enabled: true
  ip: 192.168.3.172
  name: Livingroom PC
  volume: 1.0
- enabled: true
  ip: 192.168.3.153
  name: Office PC
  volume: 1.0
- enabled: true
  ip: 192.168.0.103
  name: Office PC Management VLAN
  volume: 1.0
