# This is an example configuration. You do not need to edit it manually, but can. ScreamRouter will overwrite any changes to this file while it is running. Any comments or formatting will be lost.
groups:
  sinks:
  - enabled: true
    name: All
    sinks:
    - Livingroom
    - Bedroom
    - Bathroom
    - Office
    volume: 1.0
  - enabled: true
    name: Bedroom Group
    sinks:
    - Bedroom
    - Bathroom
    volume: 1.0
  sources:
  - enabled: true
    name: Music
    sources:
    - Server
    volume: 1.0
routes:
- enabled: true
  name: Music to All
  sink: All
  source: Music
  volume: 1.0
- enabled: true
  name: Office
  sink: Office
  source: Office PC
  volume: 1.0
- enabled: true
  name: Office 2
  sink: Office
  source: Office PC Management VLAN
  volume: 1.0
sinks:
- enabled: true
  ip: 192.168.3.178
  name: Livingroom
  port: 4010
  volume: 1.0
  bitdepth: 32
  channel_layout: stereo
  channels: 2
  samplerate: 48000
- enabled: true
  ip: 192.168.3.111
  name: Bedroom
  port: 4010
  volume: 1.0
  bitdepth: 32
  channel_layout: stereo
  channels: 2
  samplerate: 48000
- enabled: true
  ip: 192.168.3.102
  name: Bathroom
  port: 4010
  volume: 1.0
  bitdepth: 32
  channel_layout: stereo
  channels: 2
  samplerate: 48000
- enabled: true
  ip: 192.168.3.153
  name: Office
  port: 4010
  volume: 1.0
  bitdepth: 32
  channel_layout: stereo
  channels: 2
  samplerate: 48000
sources:
- enabled: true
  ip: 192.168.3.119
  name: Server
  volume: 1.0
- enabled: true
  ip: 192.168.3.172
  name: Livingroom PC
  volume: 1.0
- enabled: true
  ip: 192.168.3.153
  name: Office PC
  volume: 1.0
- enabled: true
  ip: 192.168.0.103
  name: Office PC Management VLAN
  volume: 1.0
server:
  api_port: 8080
  log_path: logs/
  receiver_port: 16401
  pipes_dir: pipes/