version: '3.8'

services:
  screamrouter:
    image: netham45/screamrouter:latest
    # Uncomment the following lines to build from source instead
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile
    container_name: screamrouter
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./cert:/app/cert
    network_mode: "host"
    environment:
      - TZ=UTC
      - API_PORT=443
