version: '3.8'

services:
  screamrouter:
    image: netham45/screamrouter:latest
    container_name: screamrouter
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./cert:/app/cert
    network_mode: "host"
    environment:
      - TZ=UTC
      - API_PORT=443
      - HTTP_PORT=80
      - CERTIFICATE=/app/cert/cert.pem
      - CERTIFICATE_KEY=/app/cert/privkey.pem
      - CONFIG_PATH=/app/config/config.yaml
      - EQUALIZER_CONFIG_PATH=/app/config/equalizers.yaml
