import { ContentCategory } from '../fullMenu/types';

export type TutorialPlacement = 'auto' | 'top' | 'bottom' | 'left' | 'right';

export interface TutorialStep {
  id: string;
  title: string;
  description: string;
  targetId?: string;
  placement?: TutorialPlacement;
  spotlightPadding?: number;
  categoryHint?: ContentCategory;
  routeHint?: string;
  showMdnsButton?: boolean;
  mdnsFilter?: 'all' | 'sources' | 'sinks';
  advanceOnMdnsSelection?: boolean;
  disableBack?: boolean;
  allowSkip?: boolean;
  isInformational?: boolean;
  skipSectionTargetId?: string;
  skipSectionLabel?: string;
}

export const TUTORIAL_VERSION = 3;

export const tutorialSteps: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to ScreamRouter',
    description:
      'This guided tour walks through configuring sources, sinks, routes, and monitoring tools. You can skip the tutorial at any time.',
    placement: 'bottom',
    allowSkip: true,
    isInformational: true,
  },
  {
    id: 'add-source-button',
    title: 'Create a Source',
    description: 'Select “Add Source” to open the source configuration form.',
    targetId: 'add-sources-button',
    placement: 'bottom',
    categoryHint: 'sources',
    routeHint: '/site',
    skipSectionTargetId: 'add-sink-button',
    skipSectionLabel: 'Skip Add Source',
  },
  {
    id: 'source-ip-input',
    title: 'Network Address',
    description:
      'Enter the source IP manually or use “Discover Devices” to populate the address automatically.',
    targetId: 'source-ip-input',
    placement: 'bottom',
    spotlightPadding: 12,
    routeHint: '/site/add-source',
    showMdnsButton: true,
    mdnsFilter: 'sources',
    advanceOnMdnsSelection: true,
    disableBack: true,
  },
  {
    id: 'source-name-input',
    title: 'Source Name',
    description: 'Provide a descriptive name so the source is easy to recognise later.',
    targetId: 'source-name-input',
    placement: 'bottom',
    spotlightPadding: 12,
    routeHint: '/site/add-source',
  },
  {
    id: 'source-volume-slider',
    title: 'Input Gain',
    description: 'Set the starting volume for the source before it is routed elsewhere.',
    targetId: 'source-volume-slider',
    placement: 'bottom',
    routeHint: '/site/add-source',
    spotlightPadding: 12,
    isInformational: true,
  },
  {
    id: 'source-delay-input',
    title: 'Source Delay',
    description: 'Optionally add a delay in milliseconds to align this source with other signals.',
    targetId: 'source-delay-input',
    placement: 'bottom',
    routeHint: '/site/add-source',
    isInformational: true,
  },
  {
    id: 'source-timeshift-slider',
    title: 'Timeshift Buffer',
    description: 'Adjust timeshift to allow rewinding or to compensate for late packets.',
    targetId: 'source-timeshift-slider',
    placement: 'bottom',
    routeHint: '/site/add-source',
    spotlightPadding: 12,
    isInformational: true,
  },
  {
    id: 'source-vnc-ip-input',
    title: 'VNC Address',
    description: 'Provide the optional VNC IP for remote control of the source device.',
    targetId: 'source-vnc-ip-input',
    placement: 'bottom',
    routeHint: '/site/add-source',
    isInformational: true,
  },
  {
    id: 'source-vnc-port-input',
    title: 'VNC Port',
    description: 'Set the VNC port if remote control is enabled for this source.',
    targetId: 'source-vnc-port-input',
    placement: 'bottom',
    routeHint: '/site/add-source',
    isInformational: true,
  },
  {
    id: 'source-submit',
    title: 'Save the Source',
    description: 'Save the source configuration. You can revisit it later if adjustments are needed.',
    targetId: 'source-submit-button',
    placement: 'top',
    routeHint: '/site/add-source',
  },
  {
    id: 'add-sink-button',
    title: 'Create a Sink',
    description: 'Return to the dashboard and choose “Add Sink” to configure an output.',
    targetId: 'add-sinks-button',
    placement: 'bottom',
    categoryHint: 'sinks',
    routeHint: '/site',
    skipSectionTargetId: 'add-route-button',
    skipSectionLabel: 'Skip Add Sink',
  },
  {
    id: 'sink-ip-input',
    title: 'Sink Address',
    description: 'Enter the sink IP or use discovery to locate it on the network.',
    targetId: 'sink-ip-input',
    placement: 'bottom',
    spotlightPadding: 12,
    routeHint: '/site/add-sink',
    showMdnsButton: true,
    mdnsFilter: 'sinks',
    advanceOnMdnsSelection: true,
    disableBack: true,
  },
  {
    id: 'sink-port-input',
    title: 'Audio Port',
    description: 'Configure the listening port for the sink connection.',
    targetId: 'sink-port-input',
    placement: 'bottom',
    routeHint: '/site/add-sink',
  },
  {
    id: 'sink-name-input',
    title: 'Sink Name',
    description: 'Name the sink so it is easy to select when creating routes.',
    targetId: 'sink-name-input',
    placement: 'bottom',
    spotlightPadding: 12,
    routeHint: '/site/add-sink',
    disableBack: true,
  },
  {
    id: 'sink-bit-depth-select',
    title: 'Bit Depth',
    description: 'Choose the audio bit depth that matches the destination device.',
    targetId: 'sink-bit-depth-select',
    placement: 'bottom',
    routeHint: '/site/add-sink',
    isInformational: true,
  },
  {
    id: 'sink-sample-rate-select',
    title: 'Sample Rate',
    description: 'Select the sample rate expected by the sink.',
    targetId: 'sink-sample-rate-select',
    placement: 'bottom',
    routeHint: '/site/add-sink',
    isInformational: true,
  },
  {
    id: 'sink-channel-layout-select',
    title: 'Channel Layout',
    description: 'Pick the channel layout that matches the sink’s speaker configuration.',
    targetId: 'sink-channel-layout-select',
    placement: 'bottom',
    routeHint: '/site/add-sink',
    isInformational: true,
  },
  {
    id: 'sink-protocol-select',
    title: 'Streaming Protocol',
    description: 'Choose the transport protocol. Selecting RTP unlocks multi-device options.',
    targetId: 'sink-protocol-select',
    placement: 'bottom',
    routeHint: '/site/add-sink',
    isInformational: true,
  },
  {
    id: 'sink-volume-slider',
    title: 'Volume',
    description: 'Set the sink volume before routes feed audio to it.',
    targetId: 'sink-volume-slider',
    placement: 'bottom',
    routeHint: '/site/add-sink',
    isInformational: true,
  },
  {
    id: 'sink-delay-input',
    title: 'Sink Delay',
    description: 'Apply a delay to the sink for timing alignment.',
    targetId: 'sink-delay-input',
    placement: 'bottom',
    routeHint: '/site/add-sink',
    isInformational: true,
  },
  {
    id: 'sink-timeshift-slider',
    title: 'Sink Timeshift',
    description: 'Configure the sink timeshift buffer for a larger delay.',
    targetId: 'sink-timeshift-slider',
    placement: 'bottom',
    routeHint: '/site/add-sink',
    isInformational: true,
  },
  {
    id: 'sink-volume-normalization-checkbox',
    title: 'Volume Normalization',
    description: 'Enable normalization to smooth differences between incoming signals.',
    targetId: 'sink-volume-normalization-checkbox',
    placement: 'bottom',
    routeHint: '/site/add-sink',
    isInformational: true,
  },
  {
    id: 'sink-time-sync-checkbox',
    title: 'Time Sync',
    description: 'Activate time synchronisation if the sink must follow a shared clock.',
    targetId: 'sink-time-sync-checkbox',
    placement: 'bottom',
    routeHint: '/site/add-sink',
    isInformational: true,
  },
  {
    id: 'sink-time-sync-delay-input',
    title: 'Sync Offset',
    description: 'Provide an additional sync delay in milliseconds when time sync is enabled.',
    targetId: 'sink-time-sync-delay-input',
    placement: 'bottom',
    routeHint: '/site/add-sink',
    isInformational: true,
  },
  {
    id: 'sink-submit',
    title: 'Save the Sink',
    description: 'Save the sink settings so it can accept routes and listeners.',
    targetId: 'sink-submit-button',
    placement: 'top',
    routeHint: '/site/add-sink',
  },
  {
    id: 'add-route-button',
    title: 'Build a Route',
    description: 'Back on the dashboard, click “Add Route” to connect sources to sinks.',
    targetId: 'add-routes-button',
    placement: 'bottom',
    categoryHint: 'routes',
    routeHint: '/site',
    skipSectionTargetId: 'resource-equalizer-button',
    skipSectionLabel: 'Skip Add Route',
  },
  {
    id: 'route-source-select',
    title: 'Select Source',
    description: 'Choose the source that feeds this route.',
    targetId: 'route-source-select',
    placement: 'bottom',
    spotlightPadding: 12,
    routeHint: '/site/add-route',
    disableBack: true,
  },
  {
    id: 'route-sink-select',
    title: 'Select Sink',
    description: 'Select the destination sink for the route.',
    targetId: 'route-sink-select',
    placement: 'bottom',
    spotlightPadding: 12,
    routeHint: '/site/add-route',
  },
  {
    id: 'route-name-input',
    title: 'Route Name',
    description: 'Confirm the auto-generated route name or enter your own.',
    targetId: 'route-name-input',
    placement: 'bottom',
    spotlightPadding: 12,
    routeHint: '/site/add-route',
  },
  {
    id: 'route-volume-slider',
    title: 'Route Volume',
    description: 'Adjust the route volume to balance the mix without altering the source or sink defaults.',
    targetId: 'route-volume-slider',
    placement: 'bottom',
    routeHint: '/site/add-route',
    isInformational: true,
  },
  {
    id: 'route-delay-input',
    title: 'Route Delay',
    description: 'Apply route-specific delay to align this path with others.',
    targetId: 'route-delay-input',
    placement: 'bottom',
    routeHint: '/site/add-route',
    isInformational: true,
  },
  {
    id: 'route-timeshift-slider',
    title: 'Route Timeshift',
    description: 'Manage the timeshift buffer used when this route is active.',
    targetId: 'route-timeshift-slider',
    placement: 'bottom',
    routeHint: '/site/add-route',
    isInformational: true,
  },
  {
    id: 'route-submit',
    title: 'Save the Route',
    description: 'Save the route to bring the connection online.',
    targetId: 'route-submit-button',
    placement: 'top',
    routeHint: '/site/add-route',
  },
  {
    id: 'resource-equalizer-button',
    title: 'Equalizer Access',
    description: 'Use the equalizer button on a card to tune the frequency response for a source, sink, or route.',
    targetId: 'resource-equalizer-button',
    placement: 'bottom',
    routeHint: '/site',
    categoryHint: 'sources',
    spotlightPadding: 12,
    isInformational: true,
  },
  {
    id: 'resource-channel-mapping-button',
    title: 'Channel Mapping',
    description: 'Open channel mapping to assign channels to speaker layouts or downstream devices.',
    targetId: 'resource-channel-mapping-button',
    placement: 'bottom',
    routeHint: '/site',
    categoryHint: 'sources',
    spotlightPadding: 12,
    isInformational: true,
  },
  {
    id: 'resource-listen-control',
    title: 'Listen In',
    description: 'Use the Listen badge on a source, route, or sink to monitor audio directly from your browser, low latency over WebRTC.',
    targetId: 'resource-listen-control',
    placement: 'bottom',
    routeHint: '/site',
    categoryHint: 'sources',
    isInformational: true,
  },
  {
    id: 'resource-enable-toggle',
    title: 'Enable or Disable',
    description: 'Toggle cards on or off to control whether a source, sink, or route participates in routing.',
    targetId: 'resource-enable-toggle',
    placement: 'bottom',
    routeHint: '/site',
    categoryHint: 'sources',
    isInformational: true,
  },
  {
    id: 'resource-favorite-toggle',
    title: 'Star Favorites',
    description: 'Use the star icon to pin frequently used sources, sinks, or routes so they stay in your Favorites list.',
    targetId: 'resource-favorite-toggle',
    placement: 'bottom',
    routeHint: '/site',
    categoryHint: 'sources',
    spotlightPadding: 12,
    isInformational: true,
  },
  {
    id: 'favorites-nav',
    title: 'Find Starred Items',
    description: 'Open the Starred Items section anytime to see every favorite grouped together for quick control.',
    targetId: 'favorites-nav-item',
    placement: 'right',
    routeHint: '/site',
    isInformational: true,
  },
  {
    id: 'resource-primary-toggle',
    title: 'Set the Primary Source',
    description: 'Mark a source as Primary so global media hotkeys and the media keys at the top of the page follow it whenever ScreamRouter is open. If the source has VNC configured, those controls can send play, pause, and track changes.',
    targetId: 'resource-primary-toggle',
    placement: 'bottom',
    routeHint: '/site',
    categoryHint: 'sources',
    spotlightPadding: 12,
    isInformational: true,
  },
  {
    id: 'tutorial-complete',
    title: 'Tutorial Complete',
    description: 'Tutorial complete. You can restart this tutorial anytime from the Help menu.',
    placement: 'bottom',
    allowSkip: false,
    routeHint: '/site',
    isInformational: true,
  },
];
