name: Build and Release Packages
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ main, master, windows_installer ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master, windows_installer ]
  workflow_dispatch:  # Allows manual triggering

# Prevent concurrent builds of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deb:
    uses: ./.github/workflows/build-debian-package.yml
    
  build-rpm:
    uses: ./.github/workflows/build-rpm-package.yml

  build-msi:
    uses: ./.github/workflows/build-msi-package.yml
  
  # Build Python wheels for all platforms (Linux x86_64/ARM64, Windows x64/x86)
  # This produces 16 wheels total (4 platforms × 4 Python versions: 3.9-3.12)
  build-wheels:
    uses: ./.github/workflows/build-wheels.yml
  
  create-release:
    needs: [build-deb, build-rpm, build-msi, build-wheels]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get commit short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
      - name: Download DEB artifact
        uses: actions/download-artifact@v4
        with:
          name: screamrouter-deb
          path: ./artifacts
          
      - name: Download RPM artifact
        uses: actions/download-artifact@v4
        with:
          name: screamrouter-rpm
          path: ./artifacts
          
      - name: Download MSI artifact
        uses: actions/download-artifact@v4
        with:
          name: screamrouter-msi # This should match the artifact name in build-msi-package.yml
          path: ./artifacts
      
      # Download Python wheels (16 wheels: 4 platforms × 4 Python versions)
      - name: Download Python wheels
        uses: actions/download-artifact@v4
        with:
          name: python-wheels
          path: ./artifacts/wheels
      
      - name: Set release details
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
            RELEASE_NAME="ScreamRouter ${VERSION}"
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            IS_PRERELEASE="false"
          else
            VERSION="development-${{ env.SHORT_SHA }}"
            RELEASE_NAME="ScreamRouter Development Build (${{ env.SHORT_SHA }})"
            TAG_NAME="build-${{ env.SHORT_SHA }}"
            IS_PRERELEASE="true"
          fi
          
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "IS_PRERELEASE=${IS_PRERELEASE}" >> $GITHUB_ENV
      
      - name: Display package files
        run: |
          echo "=== DEB/RPM/MSI Packages ==="
          ls -la ./artifacts/
          echo ""
          echo "=== Python Wheels ==="
          ls -la ./artifacts/wheels/
          echo ""
          echo "Total wheels: $(ls ./artifacts/wheels/*.whl 2>/dev/null | wc -l)"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/screamrouter_*.deb
            ./artifacts/screamrouter-*.rpm
            ./artifacts/screamrouter-*.msi
            ./artifacts/wheels/*.whl
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: ${{ env.IS_PRERELEASE == 'true' }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
