name: Build RPM Package

on:
  workflow_call:
    outputs:
      rpm_path:
        description: "Path to the built .rpm file"
        value: ${{ jobs.build-rpm-package.outputs.rpm_path }}
      version:
        description: "Version of the built package" 
        value: ${{ jobs.build-rpm-package.outputs.version }}
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-rpm-package:
    runs-on: ubuntu-latest
    outputs:
      rpm_path: ${{ steps.save_path.outputs.rpm_path }}
      version: ${{ env.VERSION }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Get commit short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm rpmlint rpmdevtools nodejs npm libmp3lame-dev gcc g++ make
        
      - name: Set version from tag or commit
        id: get_version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
          else
            VERSION="0.0.0.${{ env.SHORT_SHA }}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
      - name: Update spec file version
        run: |
          sed -i "s/Version:        1.0.0/Version:        ${{ env.VERSION }}/" rpm/screamrouter.spec
      
      - name: Setup RPM build environment
        run: |
          rpmdev-setuptree
          
      - name: Create source tarball
        run: |
          # Create a clean source directory
          mkdir -p /tmp/screamrouter-${{ env.VERSION }}
          cp -r * /tmp/screamrouter-${{ env.VERSION }}/ || true
          cd /tmp
          tar -czf ~/rpmbuild/SOURCES/screamrouter-${{ env.VERSION }}.tar.gz screamrouter-${{ env.VERSION }}
      
      - name: Build RPM package
        run: |
          # The site is built as part of the RPM spec %build section
          rpmbuild -ba rpm/screamrouter.spec
          # Copy the built RPM to the repo root
          cp ~/rpmbuild/RPMS/x86_64/screamrouter-*.rpm .
      
      - name: Save artifact path
        id: save_path
        run: |
          RPM_PATH=$(ls screamrouter-*.rpm)
          echo "rpm_path=${RPM_PATH}" >> $GITHUB_OUTPUT
          
      - name: Upload RPM package artifact
        uses: actions/upload-artifact@v4
        with:
          name: screamrouter-rpm
          path: screamrouter-*.rpm
          retention-days: 1